export const defaultResume = {
  candidateName: '',
  candidateInitials: '',
  title: '',
  phone: '',
  email: '',
  location: '',
  linkedin: '',
  totalExperience: '',
  currentCompany: '',
  currentDesignation: '',
  noticePeriod: '',
  currentCtc: '',
  expectedCtc: '',
  highestQualification: '',
  dateOfBirth: '',
  nationality: '',
  languagesKnown: [''],
  domainExperience: [''],
  toolsAndPlatforms: [''],
  keyAchievements: [''],
  professionalSummary: [''],
  expertise: [''],
  educationalQualification: [''],
  skillGroups: [
    { title: 'Functional Skills', items: [''] },
    { title: 'Tools / Platforms', items: [''] },
    { title: 'Databases / Technologies', items: [''] }
  ],
  workHistory: [{ company: 'Confidential', role: '', duration: '' }],
  technicalExperience: [{ role: '', company: '', client: '', duration: '', environment: [''], contributions: [''] }],
  projects: [{ name: '', role: '', duration: '', technologies: [''], highlights: [''] }],
  certifications: [''],
  additionalSections: [{ title: '', items: [''] }],
  confidentialLabel: 'Confidential',
  maskPersonalDetails: true
};
